### ISSUE TITLE
JRuby -Idirectory argument not passed to standby JVM

### ISSUE THREAD

**Issue by colinsurprenant** [ninjudd/drip#81] opened 2014-06-16 19:15 UTC
I discovered the following problem: when using `-Idirectory` option to the jruby command to specify the `$LOAD_PATH` directory, the first invocation works but the second time this option is not picked up by the standby JVM.

How to reproduce:

create `./drip_test.sh`

``` bash
export JAVACMD=`which drip`
export DRIP_INIT_CLASS=org.jruby.main.DripMain
export DRIP_INIT=""
RUBYLIB="$(pwd)/lib"
exec jruby -I${RUBYLIB} -e "require 'drip_test'; puts(FOO::BAR)"
```

create `./lib/drip_test.rb`

``` ruby
module FOO
  BAR="success"
end
```

``` bash
$ ./drip_test.sh
success
$ ./drip_test.sh
LoadError: no such file to load -- drip_test
  require at org/jruby/RubyKernel.java:1085
  require at /Users/colin/.rbenv/versions/jruby-1.7.11/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
   (root) at -e:1
```

A workaround is to ditch the  `-Idirectory` option and just set `RUBYLIB` in the environment and it will be picked up. 

I tried to see if there wasn't anything obvious going on and tracing `drip` shows that the arguments are being sent:

```
+ send_args
+ mkfifo /Users/colin/.drip/0.2.4/b99811adea33700618c020443af8e368808561c5/83214-1/status
+ exec
+ send_array -I/Users/colin/dev/src/elasticsearch/logstash/tmp/lib -e 'require '\''drip_test'\''; puts(FOO::BAR)'
+ local 'string=-I/Users/colin/dev/src/elasticsearch/logstash/tmp/lib -e require '\''drip_test'\''; puts(FOO::BAR)'
+ local length=92
+ ((  92 != 0  ))
+ let length=length+1
+ printf %s: 93
+ for e in '"$@"'
+ printf -- '%s\0' -I/Users/colin/dev/src/elasticsearch/logstash/tmp/lib
+ for e in '"$@"'
+ printf -- '%s\0' -e
+ for e in '"$@"'
+ printf -- '%s\0' 'require '\''drip_test'\''; puts(FOO::BAR)'
+ printf ,
+ send_array
+ local string=
+ local length=0
+ ((  0 != 0  ))
+ printf %s: 0
+ printf ,
+ send_env
```

I did not investigate much further.

**Comment by headius** [comment] 2020-07-08 21:28
This is likely a bug in the JRuby drip support, which is largely defunct now since Drip is no longer maintained.

The issue is likely that the include paths are not being properly set up in the subprocesses, either because the flag is not being passed through or because the subsequent "reset" of the config wipes it out.

I'm closing this, but if someone is interested in fixing it we would consider accepting a PR in JRuby.

**Closed by headius** 2020-07-08 21:28 UTC
